version: "3.8"

services:
  postgres:
    image: "postgres:15"
    container_name: "postgres"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: "512mb"
        reservations:
          memory: "256mb"
    shm_size: "128mb"
    user: "postgres"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - 'max_connections=100'
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "postgres", "-U", "postgres" ]
      interval: "10s"
      timeout: "2s"
      retries: 3
      start_period: "15s"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "pgdata:/var/lib/postgresql/data:rw"
    ports:
      - "127.0.0.1:5432:5432/tcp"
    networks:
      - secretsanta-network
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "unless-stopped"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - secretsanta-network
    logging: *logging
    restart: unless-stopped

  website:
    container_name: "website"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "256mb"
        reservations:
          memory: "128mb"
    depends_on:
      - "api-1"
    build:
      context: "./"
      dockerfile: "website.Dockerfile"
      target: "website"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - secretsanta-network
    logging: *logging
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: "nginx"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "128mb"
        reservations:
          memory: "64mb"
    depends_on:
      - "api-1"
      - "website"
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - secretsanta-network
    logging: *logging
    restart: unless-stopped

  api-1: &api
    container_name: "api-1"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: "256mb"
        reservations:
          memory: "256mb"
    depends_on:
      postgres:
        condition: "service_healthy"
    build:
      context: "./"
      dockerfile: "Dockerfile"
      target: "app"
    read_only: true
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - secretsanta-network
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --workers 4 --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips=*"
    logging: *logging
    restart: "unless-stopped"

volumes:
  pgdata:
  pgadmin:

networks:
  secretsanta-network:
    driver: "bridge"
    name: "secretsanta-network"
    external: false
