"""reate foreign_key

Revision ID: b7e52a2b04ec
Revises: 937698ccbfb8
Create Date: 2024-12-09 15:02:27.763824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7e52a2b04ec'
down_revision = '937698ccbfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    # ### end Alembic commands ###