"""change emailerror from id to email

Revision ID: c0722d7f83d4
Revises: 89a94d748a36
Create Date: 2024-12-06 14:22:20.995890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0722d7f83d4'
down_revision = '89a94d748a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###